### PR TITLE
Fix handling of array parameters

### PR DESCRIPTION
**Pull request by ThreeFx**
The variable `type` ironically does not have the correct type for the
check to be useful. Use `param.type` instead.

### CODE REVIEW

**Review by lsf37 — APPROVED** [review]
The change looks correct to me, but I'm slightly baffled how the original has ever worked. It is entirely possible that this code hasn't been tested in a long time.

**Comment by lsf37** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Pull request merged**
