### PR TITLE
Accept Red Hat ARM cross-compilers in `check_deps.py`

### PR DESCRIPTION
**Pull request by maybe-sybr**

### CODE REVIEW

**Comment by kent-mcleod** [comment]
Thanks! @ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
## Test results for commit 4b53b1187fd1d7e8c575a24ed66ca1e9d94decbf

### Summary

| Test name | Result |
| --- | --- |
| CAmkES - CAmkES Unit Tests - EXT-maybe-sybr-build-fedora-arm-xcompilers-29 | SUCCESSFUL |
| Code Quality - Check licenses - camkes-tool - EXT-maybe-sybr-build-fedora-arm-xcompilers-29 | SUCCESSFUL |
| Code Quality - Style - camkes-tool - EXT-maybe-sybr-build-fedora-arm-xcompilers-29 | FAILED |

### Detailed failure logs

| Project | Stage | Result summary |
| --- | --- | --- |
| Code Quality - Style - camkes-tool - EXT-maybe-sybr-build-fedora-arm-xcompilers-29 | Style check on changed files | 2 of 3 jobs failed |

**Job: style**
Build logs

    04-Dec-2019 17:18:12	Build Code Quality - Style - camkes-tool - EXT-maybe-sybr-build-fedora-arm-xcompilers-29 - style #1 (CQ-CAMKESTOOLSTYLE107-CAMKESTOOLSTYLEPR-1) started building on agent A local agent 1
    04-Dec-2019 17:18:12	I run on the Bamboo server!
    04-Dec-2019 17:18:12	Build working directory is /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-CAMKESTOOLSTYLE107-CAMKESTOOLSTYLEPR
    04-Dec-2019 17:18:12	Executing build Code Quality - Style - camkes-tool - EXT-maybe-sybr-build-fedora-arm-xcompilers-29 - style #1 (CQ-CAMKESTOOLSTYLE107-CAMKESTOOLSTYLEPR-1)
    04-Dec-2019 17:18:12	Preparing artifact 'code' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-CAMKESTOOLSTYLE107-CAMKESTOOLSTYLEPR/. (location: .)
    04-Dec-2019 17:18:12	Artifact 'code' prepared in 43.11 ms at /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-CAMKESTOOLSTYLE107-CAMKESTOOLSTYLEPR/./code.tar.gz
    04-Dec-2019 17:18:12	Running pre-build action: VCS Version Collector
    04-Dec-2019 17:18:12	Starting task 'Untar code' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    04-Dec-2019 17:18:12	+ tar xf code.tar.gz --recursive-unlink
    04-Dec-2019 17:18:12	Finished task 'Untar code' with result: Success
    04-Dec-2019 17:18:12	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    04-Dec-2019 17:18:12	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-CAMKESTOOLSTYLE107-CAMKESTOOLSTYLEPR
    04-Dec-2019 17:18:12	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    04-Dec-2019 17:18:12	Starting task 'Check style of changed files' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    04-Dec-2019 17:18:12	+ cd camkes-tool
    04-Dec-2019 17:18:12	+ xargs -d '\n' /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-CAMKESTOOLSTYLE107-CAMKESTOOLSTYLEPR/seL4_tools/misc/style.sh
    04-Dec-2019 17:18:12	++ git merge-base 4b53b1187fd1d7e8c575a24ed66ca1e9d94decbf master
    04-Dec-2019 17:18:12	+ git diff --name-only 4b53b1187fd1d7e8c575a24ed66ca1e9d94decbf a45bbc70780e25c7b16c8570910040c68a5934f3
    04-Dec-2019 17:18:13	+ git diff --exit-code
    04-Dec-2019 17:18:13	diff --git a/tools/check_deps.py b/tools/check_deps.py
    04-Dec-2019 17:18:13	index 591a696..51e6f58 100755
    04-Dec-2019 17:18:13	--- a/tools/check_deps.py
    04-Dec-2019 17:18:13	+++ b/tools/check_deps.py
    04-Dec-2019 17:18:13	@@ -21,11 +21,21 @@ from __future__ import absolute_import, division, print_function, \
    04-Dec-2019 17:18:13	 
    04-Dec-2019 17:18:13	 # This script can only import parts of the Python standard library, or it
    04-Dec-2019 17:18:13	 # becomes useless as a dependency checker.
    04-Dec-2019 17:18:13	-import abc, argparse, importlib, os, re, shutil, subprocess, sys, tempfile
    04-Dec-2019 17:18:13	+import abc
    04-Dec-2019 17:18:13	+import argparse
    04-Dec-2019 17:18:13	+import importlib
    04-Dec-2019 17:18:13	+import os
    04-Dec-2019 17:18:13	+import re
    04-Dec-2019 17:18:13	+import shutil
    04-Dec-2019 17:18:13	+import subprocess
    04-Dec-2019 17:18:13	+import sys
    04-Dec-2019 17:18:13	+import tempfile
    04-Dec-2019 17:18:13	+
    04-Dec-2019 17:18:13	 
    04-Dec-2019 17:18:13	 class CheckDepException(Exception):
    04-Dec-2019 17:18:13	     pass
    04-Dec-2019 17:18:13	 
    04-Dec-2019 17:18:13	+
    04-Dec-2019 17:18:13	 class Package(object):
    04-Dec-2019 17:18:13	 
    04-Dec-2019 17:18:13	     # Note that the following line has no effect in Python 3, but we just live
    04-Dec-2019 17:18:13	@@ -41,12 +51,14 @@ class Package(object):
    04-Dec-2019 17:18:13	     def exists(self):
    04-Dec-2019 17:18:13	         raise NotImplementedError
    04-Dec-2019 17:18:13	 
    04-Dec-2019 17:18:13	+
    04-Dec-2019 17:18:13	 class Binary(Package):
    04-Dec-2019 17:18:13	     def exists(self):
    04-Dec-2019 17:18:13	         with open(os.devnull, 'wt') as f:
    04-Dec-2019 17:18:13	             return subprocess.call(['which', self.name], stdout=f, stderr=f) \
    04-Dec-2019 17:18:13	                 == 0
    04-Dec-2019 17:18:13	 
    04-Dec-2019 17:18:13	+
    04-Dec-2019 17:18:13	 class Pylint(Binary):
    04-Dec-2019 17:18:13	     def __init__(self, name, description, min_version):
    04-Dec-2019 17:18:13	         super(Pylint, self).__init__(name, description)
    04-Dec-2019 17:18:13	@@ -63,9 +75,10 @@ class Pylint(Binary):
    04-Dec-2019 17:18:13	         version = float(m.group(1))
    04-Dec-2019 17:18:13	         if version < self.min_version:
    04-Dec-2019 17:18:13	             raise CheckDepException('found version %0.1f but need at least '
    04-Dec-2019 17:18:13	-                'version %0.1f' % (version, self.min_version))
    04-Dec-2019 17:18:13	+                                    'version %0.1f' % (version, self.min_version))
    04-Dec-2019 17:18:13	         return True
    04-Dec-2019 17:18:13	 
    04-Dec-2019 17:18:13	+
    04-Dec-2019 17:18:13	 class PythonModule(Package):
    04-Dec-2019 17:18:13	     def exists(self):
    04-Dec-2019 17:18:13	         try:
    04-Dec-2019 17:18:13	@@ -74,6 +87,7 @@ class PythonModule(Package):
    04-Dec-2019 17:18:13	         except ImportError:
    04-Dec-2019 17:18:13	             return False
    04-Dec-2019 17:18:13	 
    04-Dec-2019 17:18:13	+
    04-Dec-2019 17:18:13	 class PythonModuleWith(PythonModule):
    04-Dec-2019 17:18:13	     def __init__(self, name, description, attr):
    04-Dec-2019 17:18:13	         super(PythonModuleWith, self).__init__(name, description)
    04-Dec-2019 17:18:13	@@ -85,14 +99,16 @@ class PythonModuleWith(PythonModule):
    04-Dec-2019 17:18:13	         mod = importlib.import_module(self.name)
    04-Dec-2019 17:18:13	         if not hasattr(mod, self.attr):
    04-Dec-2019 17:18:13	             raise CheckDepException('module exists, but %s.%s not found '
    04-Dec-2019 17:18:13	-                '(upgrade required?)' % (self.name, self.attr))
    04-Dec-2019 17:18:13	+                                    '(upgrade required?)' % (self.name, self.attr))
    04-Dec-2019 17:18:13	         return True
    04-Dec-2019 17:18:13	 
    04-Dec-2019 17:18:13	+
    04-Dec-2019 17:18:13	 class CLibrary(Package):
    04-Dec-2019 17:18:13	     def exists(self):
    04-Dec-2019 17:18:13	         with open(os.devnull, 'wt') as f:
    04-Dec-2019 17:18:13	             return subprocess.call(['pkg-config', '--cflags', self.name],
    04-Dec-2019 17:18:13	-                stdout=f, stderr=f) == 0
    04-Dec-2019 17:18:13	+                                   stdout=f, stderr=f) == 0
    04-Dec-2019 17:18:13	+
    04-Dec-2019 17:18:13	 
    04-Dec-2019 17:18:13	 class Or(Package):
    04-Dec-2019 17:18:13	     def __init__(self, *packages):
    04-Dec-2019 17:18:13	@@ -103,6 +119,7 @@ class Or(Package):
    04-Dec-2019 17:18:13	     def exists(self):
    04-Dec-2019 17:18:13	         return any(p.exists() for p in self.packages)
    04-Dec-2019 17:18:13	 
    04-Dec-2019 17:18:13	+
    04-Dec-2019 17:18:13	 class CUnit(Package):
    04-Dec-2019 17:18:13	     def exists(self):
    04-Dec-2019 17:18:13	         # CUnit is misconfigured for use with `pkg-config`, so test for its
    04-Dec-2019 17:18:13	@@ -121,46 +138,50 @@ class CUnit(Package):
    04-Dec-2019 17:18:13	                     }''')
    04-Dec-2019 17:18:13	             with open(os.devnull, 'wt') as f:
    04-Dec-2019 17:18:13	                 subprocess.check_call(['gcc', 'main.c', '-lcunit'], cwd=tmp,
    04-Dec-2019 17:18:13	-                    stdout=f, stderr=f)
    04-Dec-2019 17:18:13	+                                      stdout=f, stderr=f)
    04-Dec-2019 17:18:13	             return True
    04-Dec-2019 17:18:13	         except subprocess.CalledProcessError:
    04-Dec-2019 17:18:13	             return False
    04-Dec-2019 17:18:13	         finally:
    04-Dec-2019 17:18:13	             shutil.rmtree(tmp)
    04-Dec-2019 17:18:13	 
    04-Dec-2019 17:18:13	+
    04-Dec-2019 17:18:13	 def green(string):
    04-Dec-2019 17:18:13	     return '\033[32;1m%s\033[0m' % string
    04-Dec-2019 17:18:13	 
    04-Dec-2019 17:18:13	+
    04-Dec-2019 17:18:13	 def red(string):
    04-Dec-2019 17:18:13	     return '\033[31;1m%s\033[0m' % string
    04-Dec-2019 17:18:13	 
    04-Dec-2019 17:18:13	+
    04-Dec-2019 17:18:13	 def yellow(string):
    04-Dec-2019 17:18:13	     return '\033[33m%s\033[0m' % string
    04-Dec-2019 17:18:13	 
    04-Dec-2019 17:18:13	+
    04-Dec-2019 17:18:13	 DEPENDENCIES = {
    04-Dec-2019 17:18:13	-    'CAmkES runner':(PythonModule('jinja2', 'Python templating module'),
    04-Dec-2019 17:18:13	-                     PythonModule('plyplus', 'Python parsing module'),
    04-Dec-2019 17:18:13	-                     PythonModule('ply', 'Python parsing module'),
    04-Dec-2019 17:18:13	-                     PythonModule('elftools', 'Python ELF parsing module'),
    04-Dec-2019 17:18:13	-                     PythonModule('orderedset', 'Python OrderedSet module (orderedset)'),
    04-Dec-2019 17:18:13	-                     PythonModuleWith('six', 'Python 2/3 compatibility layer', 'assertCountEqual'),
    04-Dec-2019 17:18:13	-                     PythonModule('sqlite3', 'Python SQLite module'),
    04-Dec-2019 17:18:13	-                     PythonModule('pyfdt', 'Python flattened device tree parser')),
    04-Dec-2019 17:18:13	-    'seL4':(Binary('gcc', 'C compiler'),
    04-Dec-2019 17:18:13	-            PythonModule('tempita', 'Python templating module'),
    04-Dec-2019 17:18:13	-            Binary('xmllint', 'XML validator'),
    04-Dec-2019 17:18:13	-            Binary('bash', 'shell'),
    04-Dec-2019 17:18:13	-            Binary('make', 'GNU Make build tool'),
    04-Dec-2019 17:18:13	-            Binary('cpio', 'CPIO file system tool')),
    04-Dec-2019 17:18:13	-    'CapDL translator':(Binary('stack', 'Haskell version manager'),),
    04-Dec-2019 17:18:13	-    'CAmkES test suite':(Binary('expect', 'automation utility'),
    04-Dec-2019 17:18:13	-                         Pylint('pylint', 'Python linter', 1.4),
    04-Dec-2019 17:18:13	-                         Binary('qemu-system-arm', 'ARM emulator'),
    04-Dec-2019 17:18:13	-                         Binary('qemu-system-i386', 'IA32 emulator'),
    04-Dec-2019 17:18:13	-                         PythonModule('pycparser', 'Python C parsing module'),
    04-Dec-2019 17:18:13	-                         Binary('gcc', 'C compiler'),
    04-Dec-2019 17:18:13	-                         Binary('spin', 'model checker'),
    04-Dec-2019 17:18:13	-                         Binary('sha256sum', 'file hashing utility')),
    04-Dec-2019 17:18:13	+    'CAmkES runner': (PythonModule('jinja2', 'Python templating module'),
    04-Dec-2019 17:18:13	+                      PythonModule('plyplus', 'Python parsing module'),
    04-Dec-2019 17:18:13	+                      PythonModule('ply', 'Python parsing module'),
    04-Dec-2019 17:18:13	+                      PythonModule('elftools', 'Python ELF parsing module'),
    04-Dec-2019 17:18:13	+                      PythonModule('orderedset', 'Python OrderedSet module (orderedset)'),
    04-Dec-2019 17:18:13	+                      PythonModuleWith('six', 'Python 2/3 compatibility layer', 'assertCountEqual'),
    04-Dec-2019 17:18:13	+                      PythonModule('sqlite3', 'Python SQLite module'),
    04-Dec-2019 17:18:13	+                      PythonModule('pyfdt', 'Python flattened device tree parser')),
    04-Dec-2019 17:18:13	+    'seL4': (Binary('gcc', 'C compiler'),
    04-Dec-2019 17:18:13	+             PythonModule('tempita', 'Python templating module'),
    04-Dec-2019 17:18:13	+             Binary('xmllint', 'XML validator'),
    04-Dec-2019 17:18:13	+             Binary('bash', 'shell'),
    04-Dec-2019 17:18:13	+             Binary('make', 'GNU Make build tool'),
    04-Dec-2019 17:18:13	+             Binary('cpio', 'CPIO file system tool')),
    04-Dec-2019 17:18:13	+    'CapDL translator': (Binary('stack', 'Haskell version manager'),),
    04-Dec-2019 17:18:13	+    'CAmkES test suite': (Binary('expect', 'automation utility'),
    04-Dec-2019 17:18:13	+                          Pylint('pylint', 'Python linter', 1.4),
    04-Dec-2019 17:18:13	+                          Binary('qemu-system-arm', 'ARM emulator'),
    04-Dec-2019 17:18:13	+                          Binary('qemu-system-i386', 'IA32 emulator'),
    04-Dec-2019 17:18:13	+                          PythonModule('pycparser', 'Python C parsing module'),
    04-Dec-2019 17:18:13	+                          Binary('gcc', 'C compiler'),
    04-Dec-2019 17:18:13	+                          Binary('spin', 'model checker'),
    04-Dec-2019 17:18:13	+                          Binary('sha256sum', 'file hashing utility')),
    04-Dec-2019 17:18:13	 }
    04-Dec-2019 17:18:13	 
    04-Dec-2019 17:18:13	 EXTRAS = frozenset((
    04-Dec-2019 17:18:13	@@ -211,11 +232,12 @@ EXTRAS = frozenset((
    04-Dec-2019 17:18:13	 
    04-Dec-2019 17:18:13	 ))
    04-Dec-2019 17:18:13	 
    04-Dec-2019 17:18:13	+
    04-Dec-2019 17:18:13	 def main(argv):
    04-Dec-2019 17:18:13	     parser = argparse.ArgumentParser(description='CAmkES dependency checker')
    04-Dec-2019 17:18:13	     parser.add_argument('--component', '-c', action='append',
    04-Dec-2019 17:18:13	-        choices=list(DEPENDENCIES.keys()), help='component whose dependecies '
    04-Dec-2019 17:18:13	-        'should be checked (default: all)')
    04-Dec-2019 17:18:13	+                        choices=list(DEPENDENCIES.keys()), help='component whose dependecies '
    04-Dec-2019 17:18:13	+                        'should be checked (default: all)')
    04-Dec-2019 17:18:13	     options = parser.parse_args(argv[1:])
    04-Dec-2019 17:18:13	 
    04-Dec-2019 17:18:13	     ret = 0
    04-Dec-2019 17:18:13	@@ -250,5 +272,6 @@ def main(argv):
    04-Dec-2019 17:18:13	 
    04-Dec-2019 17:18:13	     return ret
    04-Dec-2019 17:18:13	 
    04-Dec-2019 17:18:13	+
    04-Dec-2019 17:18:13	 if __name__ == '__main__':
    04-Dec-2019 17:18:13	     sys.exit(main(sys.argv))
    04-Dec-2019 17:18:13	Failing task since return code of [/var/atlassian/application-data/bamboo/temp/CQ-CAMKESTOOLSTYLE107-CAMKESTOOLSTYLEPR-1-ScriptBuildTask-1339517864431954989.sh] was 1 while expected 0
    04-Dec-2019 17:18:13	Finished task 'Check style of changed files' with result: Failed
    04-Dec-2019 17:18:13	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    04-Dec-2019 17:18:13	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-CAMKESTOOLSTYLE107-CAMKESTOOLSTYLEPR
    04-Dec-2019 17:18:13	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    04-Dec-2019 17:18:13	Starting task 'Run astyle code insights' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    04-Dec-2019 17:18:13	+ cd camkes-tool
    04-Dec-2019 17:18:13	++ echo ssh://git@bitbucket.ts.data61.csiro.au:7999/sel4/camkes-tool.git
    04-Dec-2019 17:18:13	++ cut -d/ -f4
    04-Dec-2019 17:18:13	+ bb_proj=sel4
    04-Dec-2019 17:18:13	+ /scripts/bb_code_insights/create_code_insights.sh astyle sel4 camkes-tool
    04-Dec-2019 17:18:13	++ dirname /scripts/bb_code_insights/create_code_insights.sh
    04-Dec-2019 17:18:13	+ SCRIPT_DIR=/scripts/bb_code_insights
    04-Dec-2019 17:18:13	+ BBS_URL=https://bitbucket.ts.data61.csiro.au
    04-Dec-2019 17:18:13	+ BBS_PROJECT=sel4
    04-Dec-2019 17:18:13	+ BBS_REPO=camkes-tool
    04-Dec-2019 17:18:13	+ REPORT_TO_RUN=astyle
    04-Dec-2019 17:18:13	++ git rev-parse HEAD
    04-Dec-2019 17:18:13	+ COMMIT_ID=4b53b1187fd1d7e8c575a24ed66ca1e9d94decbf
    04-Dec-2019 17:18:13	+ REPORT_KEY=camkes-tool.astyle.report
    04-Dec-2019 17:18:13	+ set +x
    04-Dec-2019 17:18:13	+ report_file=astyle_report.json
    04-Dec-2019 17:18:13	+ annotations_file=astyle_annotations.json
    04-Dec-2019 17:18:13	+ rm -f astyle_report.json astyle_annotations.json
    04-Dec-2019 17:18:13	+ /scripts/bb_code_insights/astyle
    04-Dec-2019 17:18:16	Reporting on these files:  ['tools/check_deps.py']
    04-Dec-2019 17:18:16	+ set +x
    04-Dec-2019 17:18:17	+ '[' -f astyle_report.json ']'
    04-Dec-2019 17:18:17	+ cat astyle_report.json
    04-Dec-2019 17:18:17	+ '[' -f astyle_annotations.json ']'
    04-Dec-2019 17:18:17	+ cat astyle_annotations.json
    04-Dec-2019 17:18:17	{"data":[{"title":"Total number of files with incorrect style","value":1},{"title":"Total number of lines with incorrect style","value":30}],"createdDate":1575440296734,"key":"camkes-tool.astyle.report","title":"Code style"}{"title": "Code style", "data": [{"title": "Total number of files with incorrect style", "value": 1}, {"title": "Total number of lines with incorrect style", "value": 30}]}{"annotations": [{"path": "tools/check_deps.py", "line": 24, "message": "There are 1 line(s) of incorrect style here.", "severity": "HIGH"}, {"path": "tools/check_deps.py", "line": 28, "message": "There are 0 line(s) of incorrect style here.", "severity": "HIGH"}, {"path": "tools/check_deps.py", "line": 43, "message": "There are 0 line(s) of incorrect style here.", "severity": "HIGH"}, {"path": "tools/check_deps.py", "line": 49, "message": "There are 0 line(s) of incorrect style here.", "severity": "HIGH"}, {"path": "tools/check_deps.py", "line": 66, "message": "There are 1 line(s) of incorrect style here.", "severity": "HIGH"}, {"path": "tools/check_deps.py", "line": 68, "message": "There are 0 line(s) of incorrect style here.", "severity": "HIGH"}, {"path": "tools/check_deps.py", "line": 76, "message": "There are 0 line(s) of incorrect style here.", "severity": "HIGH"}, {"path": "tools/check_deps.py", "line": 88, "message": "There are 1 line(s) of incorrect style here.", "severity": "HIGH"}, {"path": "tools/check_deps.py", "line": 90, "message": "There are 0 line(s) of incorrect style here.", "severity": "HIGH"}, {"path": "tools/check_deps.py", "line": 95, "message": "There are 1 line(s) of incorrect style here.", "severity": "HIGH"}, {"path": "tools/check_deps.py", "line": 105, "message": "There are 0 line(s) of incorrect style here.", "severity": "HIGH"}, {"path": "tools/check_deps.py", "line": 124, "message": "There are 1 line(s) of incorrect style here.", "severity": "HIGH"}, {"path": "tools/check_deps.py", "line": 130, "message": "There are 0 line(s) of incorrect style here.", "severity": "HIGH"}, {"path": "tools/check_deps.py", "line": 133, "message": "There are 0 line(s) of incorrect style here.", "severity": "HIGH"}, {"path": "tools/check_deps.py", "line": 136, "message": "There are 0 line(s) of incorrect style here.", "severity": "HIGH"}, {"path": "tools/check_deps.py", "line": 139, "message": "There are 0 line(s) of incorrect style here.", "severity": "HIGH"}, {"path": "tools/check_deps.py", "line": 141, "message": "There are 23 line(s) of incorrect style here.", "severity": "HIGH"}, {"path": "tools/check_deps.py", "line": 213, "message": "There are 0 line(s) of incorrect style here.", "severity": "HIGH"}, {"path": "tools/check_deps.py", "line": 217, "message": "There are 2 line(s) of incorrect style here.", "severity": "HIGH"}, {"path": "tools/check_deps.py", "line": 252, "message": "There are 0 line(s) of incorrect style here.", "severity": "HIGH"}]}
    04-Dec-2019 17:18:17	Finished task 'Run astyle code insights' with result: Success
    04-Dec-2019 17:18:17	Running post build plugin 'NCover Results Collector'
    04-Dec-2019 17:18:17	Running post build plugin 'Artifact Copier'
    04-Dec-2019 17:18:17	Running post build plugin 'npm Cache Cleanup'
    04-Dec-2019 17:18:17	Running post build plugin 'Clover Results Collector'
    04-Dec-2019 17:18:17	Running post build plugin 'Docker Container Cleanup'
    04-Dec-2019 17:18:17	Successfully removed working directory at '/var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-CAMKESTOOLSTYLE107-CAMKESTOOLSTYLEPR'
    04-Dec-2019 17:18:17	Finalising the build...
    04-Dec-2019 17:18:17	Stopping timer.
    04-Dec-2019 17:18:17	Build CQ-CAMKESTOOLSTYLE107-CAMKESTOOLSTYLEPR-1 completed.
    04-Dec-2019 17:18:17	Running on server: post build plugin 'NCover Results Collector'
    04-Dec-2019 17:18:17	Running on server: post build plugin 'Build Hanging Detection Configuration'
    04-Dec-2019 17:18:17	Running on server: post build plugin 'Clover Delta Calculator'
    04-Dec-2019 17:18:17	Running on server: post build plugin 'Maven Dependencies Postprocessor'
    04-Dec-2019 17:18:17	All post build plugins have finished
    04-Dec-2019 17:18:17	Generating build results summary...
    04-Dec-2019 17:18:17	Saving build results to disk...
    04-Dec-2019 17:18:17	Logging substituted variables...
    04-Dec-2019 17:18:17	Indexing build results...
    04-Dec-2019 17:18:17	Finished building CQ-CAMKESTOOLSTYLE107-CAMKESTOOLSTYLEPR-1.

**Job: gitlint**
Build logs

    04-Dec-2019 17:18:12	Build Code Quality - Style - camkes-tool - EXT-maybe-sybr-build-fedora-arm-xcompilers-29 - gitlint #1 (CQ-CAMKESTOOLSTYLE107-CAMKESTOOLGITLINTPR-1) started building on agent A local agent 2
    04-Dec-2019 17:18:12	I run on the Bamboo server!
    04-Dec-2019 17:18:12	Build working directory is /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-CAMKESTOOLSTYLE107-CAMKESTOOLGITLINTPR
    04-Dec-2019 17:18:12	Executing build Code Quality - Style - camkes-tool - EXT-maybe-sybr-build-fedora-arm-xcompilers-29 - gitlint #1 (CQ-CAMKESTOOLSTYLE107-CAMKESTOOLGITLINTPR-1)
    04-Dec-2019 17:18:12	Preparing artifact 'code' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-CAMKESTOOLSTYLE107-CAMKESTOOLGITLINTPR/. (location: .)
    04-Dec-2019 17:18:12	Artifact 'code' prepared in 35.04 ms at /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-CAMKESTOOLSTYLE107-CAMKESTOOLGITLINTPR/./code.tar.gz
    04-Dec-2019 17:18:12	Running pre-build action: VCS Version Collector
    04-Dec-2019 17:18:13	Starting task 'Untar code' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    04-Dec-2019 17:18:13	+ tar xf code.tar.gz --recursive-unlink
    04-Dec-2019 17:18:13	Finished task 'Untar code' with result: Success
    04-Dec-2019 17:18:13	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    04-Dec-2019 17:18:13	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-CAMKESTOOLSTYLE107-CAMKESTOOLGITLINTPR
    04-Dec-2019 17:18:13	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    04-Dec-2019 17:18:13	Starting task 'Lint commit messages' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    04-Dec-2019 17:18:13	+ cd camkes-tool
    04-Dec-2019 17:18:13	+ gitlint --commits master..4b53b1187fd1d7e8c575a24ed66ca1e9d94decbf --config /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-CAMKESTOOLSTYLE107-CAMKESTOOLGITLINTPR/seL4_tools/misc/.gitlint
    04-Dec-2019 17:18:16	3: B6 Body message is missing
    04-Dec-2019 17:18:16	Failing task since return code of [/var/atlassian/application-data/bamboo/temp/CQ-CAMKESTOOLSTYLE107-CAMKESTOOLGITLINTPR-1-ScriptBuildTask-1543370488305644286.sh] was 1 while expected 0
    04-Dec-2019 17:18:16	Finished task 'Lint commit messages' with result: Failed
    04-Dec-2019 17:18:16	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    04-Dec-2019 17:18:16	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-CAMKESTOOLSTYLE107-CAMKESTOOLGITLINTPR
    04-Dec-2019 17:18:16	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    04-Dec-2019 17:18:16	Running post build plugin 'NCover Results Collector'
    04-Dec-2019 17:18:16	Running post build plugin 'Artifact Copier'
    04-Dec-2019 17:18:16	Running post build plugin 'npm Cache Cleanup'
    04-Dec-2019 17:18:16	Running post build plugin 'Clover Results Collector'
    04-Dec-2019 17:18:16	Running post build plugin 'Docker Container Cleanup'
    04-Dec-2019 17:18:16	Successfully removed working directory at '/var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-CAMKESTOOLSTYLE107-CAMKESTOOLGITLINTPR'
    04-Dec-2019 17:18:16	Finalising the build...
    04-Dec-2019 17:18:16	Stopping timer.
    04-Dec-2019 17:18:16	Build CQ-CAMKESTOOLSTYLE107-CAMKESTOOLGITLINTPR-1 completed.
    04-Dec-2019 17:18:16	Running on server: post build plugin 'NCover Results Collector'
    04-Dec-2019 17:18:16	Running on server: post build plugin 'Build Hanging Detection Configuration'
    04-Dec-2019 17:18:16	Running on server: post build plugin 'Clover Delta Calculator'
    04-Dec-2019 17:18:16	Running on server: post build plugin 'Maven Dependencies Postprocessor'
    04-Dec-2019 17:18:16	All post build plugins have finished
    04-Dec-2019 17:18:16	Generating build results summary...
    04-Dec-2019 17:18:16	Saving build results to disk...
    04-Dec-2019 17:18:16	Logging substituted variables...
    04-Dec-2019 17:18:16	Indexing build results...
    04-Dec-2019 17:18:16	Finished building CQ-CAMKESTOOLSTYLE107-CAMKESTOOLGITLINTPR-1.


This is the most I can report on right now, sorry!

**Comment by kent-mcleod** [comment]
As long as the changes on external PRs aren't actively taking a file's style conformance further away from the style guide we're usually happy to merge changes with a failing style test in order to minimise friction associated with submitting a patch.

**Pull request merged**
