### PR TITLE
output: simplify message

### PR DESCRIPTION
**Pull request by axel-h**
trivial change just to make the message shorter and easier to read

### CODE REVIEW

**Comment by kent-mcleod** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Comment by nomadeel** [comment]
Looks good, changed the commit prefix to be 'trivial' and made the subject line just a tiny bit clearer. Merging.

**Comment by nomadeel** [comment]
Also rebased against master.

**Pull request merged**
