### PR TITLE
templates: add missing return statement

### PR DESCRIPTION
**Pull request by axel-h**
fix build breaker about control flow path with no return statement.

### CODE REVIEW

**Comment by axel-h** [comment]
update patch, preserve the return codes and avoid a warning that the return codes are ignored

**Comment by nomadeel** [comment]
@ssrg-bamboo `test`

**Comment by LukeMondy** [comment]
@ssrg-bamboo `test`
Seems like the first notification didn't get through

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Pull request merged**
