### PR TITLE
Release 3.9.0

### PR DESCRIPTION
**Pull request by oliver-wm**
October release.

### CODE REVIEW

**Comment by walle-whale** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Comment by ssrg-bamboo** [comment]
## Test results for commit f61b8e9dc29093d816b45daaeeb7fdec2b87c24f

### Summary

#### NOTE: some test results have been updated!

| Test name | Result |
| --- | --- |
| CAmkES - CAmkES Unit Tests - EXT-seL4-October-release-43 | SUCCESSFUL |
| Code Quality - Check licenses - camkes-tool - EXT-seL4-October-release-43 | SUCCESSFUL |
| Code Quality - Style - camkes-tool - EXT-seL4-October-release-43 | FAILED |

### Detailed failure logs

| Project | Stage | Result summary |
| --- | --- | --- |
| Code Quality - Style - camkes-tool - EXT-seL4-October-release-43 | Style check on changed files | 1 of 3 jobs failed |

**Job: shell**
Build logs

    05-Nov-2020 11:42:14	Build Code Quality - Style - camkes-tool - EXT-seL4-October-release-43 - shell #2 (CQ-CAMKESTOOLSTYLE185-CAMKESTOOLSHELLPR-2) started building on agent A local agent 2
    05-Nov-2020 11:42:14	I run on the Bamboo server!
    05-Nov-2020 11:42:14	Build working directory is /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-CAMKESTOOLSTYLE185-CAMKESTOOLSHELLPR
    05-Nov-2020 11:42:14	Executing build Code Quality - Style - camkes-tool - EXT-seL4-October-release-43 - shell #2 (CQ-CAMKESTOOLSTYLE185-CAMKESTOOLSHELLPR-2)
    05-Nov-2020 11:42:14	Preparing artifact 'code' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-CAMKESTOOLSTYLE185-CAMKESTOOLSHELLPR/. (location: .)
    05-Nov-2020 11:42:14	Artifact 'code' prepared in 22.17 ms at /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-CAMKESTOOLSTYLE185-CAMKESTOOLSHELLPR/./code.tar.gz
    05-Nov-2020 11:42:14	Running pre-build action: VCS Version Collector
    05-Nov-2020 11:42:14	Starting task 'Untar code' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    05-Nov-2020 11:42:14	+ tar xf code.tar.gz --recursive-unlink
    05-Nov-2020 11:42:14	Finished task 'Untar code' with result: Success
    05-Nov-2020 11:42:14	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    05-Nov-2020 11:42:14	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-CAMKESTOOLSTYLE185-CAMKESTOOLSHELLPR
    05-Nov-2020 11:42:14	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    05-Nov-2020 11:42:14	Starting task 'Check validity of shell scripts' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    05-Nov-2020 11:42:14	+ cd camkes-tool
    05-Nov-2020 11:42:14	++ git diff --name-only f61b8e9dc29093d816b45daaeeb7fdec2b87c24f fa0d94d4a3021ba23b92b07e764d4a3e8d371e6e
    05-Nov-2020 11:42:14	+ echo 'Checking shell style and syntax on CHANGES
    05-Nov-2020 11:42:14	Checking shell style and syntax on CHANGES
    05-Nov-2020 11:42:14	VERSION'
    05-Nov-2020 11:42:14	VERSION
    05-Nov-2020 11:42:14	+ git diff --name-only f61b8e9dc29093d816b45daaeeb7fdec2b87c24f fa0d94d4a3021ba23b92b07e764d4a3e8d371e6e
    05-Nov-2020 11:42:14	+ xargs -d '\n' /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-CAMKESTOOLSTYLE185-CAMKESTOOLSHELLPR/seL4_tools/misc/is-valid-shell-script
    05-Nov-2020 11:42:14	xargs: /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-CAMKESTOOLSTYLE185-CAMKESTOOLSHELLPR/seL4_tools/misc/is-valid-shell-script: No such file or directory
    05-Nov-2020 11:42:14	Failing task since return code of [/var/atlassian/application-data/bamboo/temp/CQ-CAMKESTOOLSTYLE185-CAMKESTOOLSHELLPR-2-ScriptBuildTask-9066084632768061993.sh] was 127 while expected 0
    05-Nov-2020 11:42:14	Finished task 'Check validity of shell scripts' with result: Failed
    05-Nov-2020 11:42:14	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    05-Nov-2020 11:42:14	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-CAMKESTOOLSTYLE185-CAMKESTOOLSHELLPR
    05-Nov-2020 11:42:14	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    05-Nov-2020 11:42:14	Running post build plugin 'NCover Results Collector'
    05-Nov-2020 11:42:14	Running post build plugin 'Artifact Copier'
    05-Nov-2020 11:42:14	Running post build plugin 'npm Cache Cleanup'
    05-Nov-2020 11:42:14	Running post build plugin 'Clover Results Collector'
    05-Nov-2020 11:42:14	Running post build plugin 'Docker Container Cleanup'
    05-Nov-2020 11:42:14	Successfully removed working directory at '/var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-CAMKESTOOLSTYLE185-CAMKESTOOLSHELLPR'
    05-Nov-2020 11:42:14	Finalising the build...
    05-Nov-2020 11:42:14	Stopping timer.
    05-Nov-2020 11:42:14	Build CQ-CAMKESTOOLSTYLE185-CAMKESTOOLSHELLPR-2 completed.
    05-Nov-2020 11:42:14	Running on server: post build plugin 'NCover Results Collector'
    05-Nov-2020 11:42:14	Running on server: post build plugin 'Build Hanging Detection Configuration'
    05-Nov-2020 11:42:14	Running on server: post build plugin 'Clover Delta Calculator'
    05-Nov-2020 11:42:14	Running on server: post build plugin 'Maven Dependencies Postprocessor'
    05-Nov-2020 11:42:14	All post build plugins have finished
    05-Nov-2020 11:42:14	Generating build results summary...
    05-Nov-2020 11:42:15	Saving build results to disk...
    05-Nov-2020 11:42:15	Store variable context...
    05-Nov-2020 11:42:15	Indexing build results...
    05-Nov-2020 11:42:15	Finished building CQ-CAMKESTOOLSTYLE185-CAMKESTOOLSHELLPR-2.


This is the most I can report on right now, sorry!

**Comment by ssrg-bamboo** [comment]
## Test results for commit f61b8e9dc29093d816b45daaeeb7fdec2b87c24f

### Summary

#### NOTE: some test results have been updated!

| Test name | Result |
| --- | --- |
| CAmkES - CAmkES Unit Tests - EXT-seL4-October-release-43 | SUCCESSFUL |
| Code Quality - Check licenses - camkes-tool - EXT-seL4-October-release-43 | SUCCESSFUL |
| Code Quality - Style - camkes-tool - EXT-seL4-October-release-43 | FAILED |

### Detailed failure logs

| Project | Stage | Result summary |
| --- | --- | --- |
| Code Quality - Style - camkes-tool - EXT-seL4-October-release-43 | Style check on changed files | 1 of 3 jobs failed |

**Job: shell**
Build logs

    05-Nov-2020 11:42:14	Build Code Quality - Style - camkes-tool - EXT-seL4-October-release-43 - shell #2 (CQ-CAMKESTOOLSTYLE185-CAMKESTOOLSHELLPR-2) started building on agent A local agent 2
    05-Nov-2020 11:42:14	I run on the Bamboo server!
    05-Nov-2020 11:42:14	Build working directory is /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-CAMKESTOOLSTYLE185-CAMKESTOOLSHELLPR
    05-Nov-2020 11:42:14	Executing build Code Quality - Style - camkes-tool - EXT-seL4-October-release-43 - shell #2 (CQ-CAMKESTOOLSTYLE185-CAMKESTOOLSHELLPR-2)
    05-Nov-2020 11:42:14	Preparing artifact 'code' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-CAMKESTOOLSTYLE185-CAMKESTOOLSHELLPR/. (location: .)
    05-Nov-2020 11:42:14	Artifact 'code' prepared in 22.17 ms at /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-CAMKESTOOLSTYLE185-CAMKESTOOLSHELLPR/./code.tar.gz
    05-Nov-2020 11:42:14	Running pre-build action: VCS Version Collector
    05-Nov-2020 11:42:14	Starting task 'Untar code' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    05-Nov-2020 11:42:14	+ tar xf code.tar.gz --recursive-unlink
    05-Nov-2020 11:42:14	Finished task 'Untar code' with result: Success
    05-Nov-2020 11:42:14	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    05-Nov-2020 11:42:14	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-CAMKESTOOLSTYLE185-CAMKESTOOLSHELLPR
    05-Nov-2020 11:42:14	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    05-Nov-2020 11:42:14	Starting task 'Check validity of shell scripts' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    05-Nov-2020 11:42:14	+ cd camkes-tool
    05-Nov-2020 11:42:14	++ git diff --name-only f61b8e9dc29093d816b45daaeeb7fdec2b87c24f fa0d94d4a3021ba23b92b07e764d4a3e8d371e6e
    05-Nov-2020 11:42:14	+ echo 'Checking shell style and syntax on CHANGES
    05-Nov-2020 11:42:14	Checking shell style and syntax on CHANGES
    05-Nov-2020 11:42:14	VERSION'
    05-Nov-2020 11:42:14	VERSION
    05-Nov-2020 11:42:14	+ git diff --name-only f61b8e9dc29093d816b45daaeeb7fdec2b87c24f fa0d94d4a3021ba23b92b07e764d4a3e8d371e6e
    05-Nov-2020 11:42:14	+ xargs -d '\n' /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-CAMKESTOOLSTYLE185-CAMKESTOOLSHELLPR/seL4_tools/misc/is-valid-shell-script
    05-Nov-2020 11:42:14	xargs: /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-CAMKESTOOLSTYLE185-CAMKESTOOLSHELLPR/seL4_tools/misc/is-valid-shell-script: No such file or directory
    05-Nov-2020 11:42:14	Failing task since return code of [/var/atlassian/application-data/bamboo/temp/CQ-CAMKESTOOLSTYLE185-CAMKESTOOLSHELLPR-2-ScriptBuildTask-9066084632768061993.sh] was 127 while expected 0
    05-Nov-2020 11:42:14	Finished task 'Check validity of shell scripts' with result: Failed
    05-Nov-2020 11:42:14	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    05-Nov-2020 11:42:14	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-CAMKESTOOLSTYLE185-CAMKESTOOLSHELLPR
    05-Nov-2020 11:42:14	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    05-Nov-2020 11:42:14	Running post build plugin 'NCover Results Collector'
    05-Nov-2020 11:42:14	Running post build plugin 'Artifact Copier'
    05-Nov-2020 11:42:14	Running post build plugin 'npm Cache Cleanup'
    05-Nov-2020 11:42:14	Running post build plugin 'Clover Results Collector'
    05-Nov-2020 11:42:14	Running post build plugin 'Docker Container Cleanup'
    05-Nov-2020 11:42:14	Successfully removed working directory at '/var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-CAMKESTOOLSTYLE185-CAMKESTOOLSHELLPR'
    05-Nov-2020 11:42:14	Finalising the build...
    05-Nov-2020 11:42:14	Stopping timer.
    05-Nov-2020 11:42:14	Build CQ-CAMKESTOOLSTYLE185-CAMKESTOOLSHELLPR-2 completed.
    05-Nov-2020 11:42:14	Running on server: post build plugin 'NCover Results Collector'
    05-Nov-2020 11:42:14	Running on server: post build plugin 'Build Hanging Detection Configuration'
    05-Nov-2020 11:42:14	Running on server: post build plugin 'Clover Delta Calculator'
    05-Nov-2020 11:42:14	Running on server: post build plugin 'Maven Dependencies Postprocessor'
    05-Nov-2020 11:42:14	All post build plugins have finished
    05-Nov-2020 11:42:14	Generating build results summary...
    05-Nov-2020 11:42:15	Saving build results to disk...
    05-Nov-2020 11:42:15	Store variable context...
    05-Nov-2020 11:42:15	Indexing build results...
    05-Nov-2020 11:42:15	Finished building CQ-CAMKESTOOLSTYLE185-CAMKESTOOLSHELLPR-2.


This is the most I can report on right now, sorry!

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Comment by axel-h** [comment]
closing this draft, the release has been made

**Pull request closed without merging**
