### PR TITLE
parser: add command line to exception

### PR DESCRIPTION
**Pull request by axel-h**

### CODE REVIEW

**Review by kent-mcleod — APPROVED** [review]
Cool!

**Review by xurtis — APPROVED** [review]

**Comment by axel-h** [comment]
could you merge this? This can come really handy sometimes during development because it saves time hunting some obscure errors.

**Comment by xurtis** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Comment by axel-h** [comment]
can we merge this?

**Pull request merged**
