### PR TITLE
trivial: SPDX comment

### PR DESCRIPTION
**Pull request by lsf37**
(plus style run for that file)

### CODE REVIEW

**Review by kent-mcleod — APPROVED** [review]

**Comment by oliver-wm** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
## Test results for commit 3c72e418c7bf1fd68762074e7f91a9118c6eb013

### Summary

| Test name | Result |
| --- | --- |
| CAmkES - CAmkES Unit Tests - EXT-seL4-comment-60 | FAILED |
| Code Quality - Check licenses - camkes-tool - EXT-seL4-comment-60 | SUCCESSFUL |
| Code Quality - Reuse License Check - camkes-tool - EXT-seL4-comment-60 | SUCCESSFUL |
| Code Quality - Signed-off-by - camkes-tool - EXT-seL4-comment-60 | SUCCESSFUL |
| Code Quality - Style - camkes-tool - EXT-seL4-comment-60 | SUCCESSFUL |

### Detailed failure logs

| Project | Stage | Result summary |
| --- | --- | --- |
| CAmkES - CAmkES Unit Tests - EXT-seL4-comment-60 | Build | 1 of 1 job failed |

**Job: Run tests**
Build logs

    18-Mar-2021 01:01:25	Build CAmkES - CAmkES Unit Tests - EXT-seL4-comment-60 - Run tests #1 (CAMKES-CUT202-UNIT-1) started building on agent Elastic Agent on i-0b3bb415fbb382601, bamboo version: 7.1.4
    18-Mar-2021 01:01:25	Elastic agent on instance i-0b3bb415fbb382601
    18-Mar-2021 01:01:25	Build working directory is /home/bamboo/bamboo-agent-home/xml-data/build-dir/CAMKES-CUT202-UNIT
    18-Mar-2021 01:01:25	Unable to find image 'trustworthysystems/camkes:latest' locally
    18-Mar-2021 01:01:27	latest: Pulling from trustworthysystems/camkes
    18-Mar-2021 01:01:27	afb6ec6fdc1c: Already exists
    18-Mar-2021 01:01:27	cd10e1a6ccac: Already exists
    18-Mar-2021 01:01:27	2253bb7e58b4: Already exists
    18-Mar-2021 01:01:27	9f94314b0dfa: Already exists
    18-Mar-2021 01:01:27	7b2dce511d06: Already exists
    18-Mar-2021 01:01:27	5eabb367af56: Pulling fs layer
    18-Mar-2021 01:01:27	23b2448513ab: Pulling fs layer
    18-Mar-2021 01:01:28	5eabb367af56: Verifying Checksum
    18-Mar-2021 01:01:28	5eabb367af56: Download complete
    18-Mar-2021 01:01:28	5eabb367af56: Pull complete
    18-Mar-2021 01:01:34	23b2448513ab: Verifying Checksum
    18-Mar-2021 01:01:34	23b2448513ab: Download complete
    18-Mar-2021 01:01:57	23b2448513ab: Pull complete
    18-Mar-2021 01:01:57	Digest: sha256:44c99a77cc38a73d0f435bc6a886532801927d1e765110370a84eb9e0d6e15fd
    18-Mar-2021 01:01:57	Status: Downloaded newer image for trustworthysystems/camkes:latest
    18-Mar-2021 01:02:04	673fe51555c662132ac20f2bd3c4ac49929e04515b9b47de762800533fe5c527
    18-Mar-2021 01:02:05	Executing build CAmkES - CAmkES Unit Tests - EXT-seL4-comment-60 - Run tests #1 (CAMKES-CUT202-UNIT-1)
    18-Mar-2021 01:02:05	Preparing artifact 'code' for use at /home/bamboo/bamboo-agent-home/xml-data/build-dir/CAMKES-CUT202-UNIT/. (location: .)
    18-Mar-2021 01:02:06	Artifact 'code' prepared in 222.6 ms at /home/bamboo/bamboo-agent-home/xml-data/build-dir/CAMKES-CUT202-UNIT/code.tar.gz
    18-Mar-2021 01:02:06	Running pre-build action: VCS Version Collector
    18-Mar-2021 01:02:06	Starting task 'Untar code' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    18-Mar-2021 01:02:07	+ tar xf code.tar.gz --recursive-unlink
    18-Mar-2021 01:02:07	Finished task 'Untar code' with result: Success
    18-Mar-2021 01:02:07	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    18-Mar-2021 01:02:08	+ chmod -R o+rwx /home/bamboo/bamboo-agent-home/xml-data/build-dir/CAMKES-CUT202-UNIT
    18-Mar-2021 01:02:08	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    18-Mar-2021 01:02:08	Starting task 'Set GitHub Status [camkes-tool: CAmkES Unit Tests]' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    18-Mar-2021 01:02:09	+ SHA=3c72e418c7bf1fd68762074e7f91a9118c6eb013
    18-Mar-2021 01:02:09	+ RESULT=pending
    18-Mar-2021 01:02:09	+ curl -u ssrg-bamboo:******** -X POST -H 'Accept: application/vnd.github.v3+json' https://api.github.com/repos/seL4/camkes-tool/statuses/3c72e418c7bf1fd68762074e7f91a9118c6eb013 -d '{"state":"pending","context":"CAmkES Unit Tests"}'
    18-Mar-2021 01:02:09	  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
    18-Mar-2021 01:02:09	                                 Dload  Upload   Total   Spent    Left  Speed
    18-Mar-2021 01:02:09	
    18-Mar-2021 01:02:09	  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
    18-Mar-2021 01:02:09	{
    18-Mar-2021 01:02:09	100  1560  100  1511  100    49   3109    100 --:--:-- --:--:-- --:--:--  3209
    18-Mar-2021 01:02:09	  "url": "https://api.github.com/repos/seL4/camkes-tool/statuses/3c72e418c7bf1fd68762074e7f91a9118c6eb013",
    18-Mar-2021 01:02:09	  "avatar_url": "https://avatars.githubusercontent.com/u/17556722?v=4",
    18-Mar-2021 01:02:09	  "id": 12517871281,
    18-Mar-2021 01:02:09	  "node_id": "MDEzOlN0YXR1c0NvbnRleHQxMjUxNzg3MTI4MQ==",
    18-Mar-2021 01:02:09	  "state": "pending",
    18-Mar-2021 01:02:09	  "description": null,
    18-Mar-2021 01:02:09	  "target_url": null,
    18-Mar-2021 01:02:09	  "context": "CAmkES Unit Tests",
    18-Mar-2021 01:02:09	  "created_at": "2021-03-18T01:02:09Z",
    18-Mar-2021 01:02:09	  "updated_at": "2021-03-18T01:02:09Z",
    18-Mar-2021 01:02:09	  "creator": {
    18-Mar-2021 01:02:09	    "login": "ssrg-bamboo",
    18-Mar-2021 01:02:09	    "id": 17556722,
    18-Mar-2021 01:02:09	    "node_id": "MDQ6VXNlcjE3NTU2NzIy",
    18-Mar-2021 01:02:09	    "avatar_url": "https://avatars.githubusercontent.com/u/17556722?v=4",
    18-Mar-2021 01:02:09	    "gravatar_id": "",
    18-Mar-2021 01:02:09	    "url": "https://api.github.com/users/ssrg-bamboo",
    18-Mar-2021 01:02:09	    "html_url": "https://github.com/ssrg-bamboo",
    18-Mar-2021 01:02:09	    "followers_url": "https://api.github.com/users/ssrg-bamboo/followers",
    18-Mar-2021 01:02:09	    "following_url": "https://api.github.com/users/ssrg-bamboo/following{/other_user}",
    18-Mar-2021 01:02:09	    "gists_url": "https://api.github.com/users/ssrg-bamboo/gists{/gist_id}",
    18-Mar-2021 01:02:09	    "starred_url": "https://api.github.com/users/ssrg-bamboo/starred{/owner}{/repo}",
    18-Mar-2021 01:02:09	    "subscriptions_url": "https://api.github.com/users/ssrg-bamboo/subscriptions",
    18-Mar-2021 01:02:09	    "organizations_url": "https://api.github.com/users/ssrg-bamboo/orgs",
    18-Mar-2021 01:02:09	    "repos_url": "https://api.github.com/users/ssrg-bamboo/repos",
    18-Mar-2021 01:02:09	    "events_url": "https://api.github.com/users/ssrg-bamboo/events{/privacy}",
    18-Mar-2021 01:02:09	    "received_events_url": "https://api.github.com/users/ssrg-bamboo/received_events",
    18-Mar-2021 01:02:09	    "type": "User",
    18-Mar-2021 01:02:09	    "site_admin": false
    18-Mar-2021 01:02:09	  }
    18-Mar-2021 01:02:09	}
    18-Mar-2021 01:02:09	Finished task 'Set GitHub Status [camkes-tool: CAmkES Unit Tests]' with result: Success
    18-Mar-2021 01:02:09	Starting task 'Run unit tests' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    18-Mar-2021 01:02:10	+ PYTHONPATH=../capdl/python-capdl-tool
    18-Mar-2021 01:02:10	+ nosetests --exe --ignore-file=testvisualcamkes.py --with-xunit --xunit-file=../parsed_results.xml
    18-Mar-2021 01:02:13	S...............................................................................................................................................................................E
    18-Mar-2021 01:02:13	======================================================================
    18-Mar-2021 01:02:13	ERROR: Failure: ModuleNotFoundError (No module named 'capdl')
    18-Mar-2021 01:02:13	----------------------------------------------------------------------
    18-Mar-2021 01:02:13	Traceback (most recent call last):
    18-Mar-2021 01:02:13	  File "/usr/local/lib/python3.8/dist-packages/nose/failure.py", line 39, in runTest
    18-Mar-2021 01:02:13	    raise self.exc_val.with_traceback(self.tb)
    18-Mar-2021 01:02:13	  File "/usr/local/lib/python3.8/dist-packages/nose/loader.py", line 417, in loadTestsFromName
    18-Mar-2021 01:02:13	    module = self.importer.importFromPath(
    18-Mar-2021 01:02:13	  File "/usr/local/lib/python3.8/dist-packages/nose/importer.py", line 47, in importFromPath
    18-Mar-2021 01:02:13	    return self.importFromDir(dir_path, fqname)
    18-Mar-2021 01:02:13	  File "/usr/local/lib/python3.8/dist-packages/nose/importer.py", line 94, in importFromDir
    18-Mar-2021 01:02:13	    mod = load_module(part_fqname, fh, filename, desc)
    18-Mar-2021 01:02:13	  File "/usr/lib/python3.8/imp.py", line 244, in load_module
    18-Mar-2021 01:02:13	    return load_package(name, filename)
    18-Mar-2021 01:02:13	  File "/usr/lib/python3.8/imp.py", line 216, in load_package
    18-Mar-2021 01:02:13	    return _load(spec)
    18-Mar-2021 01:02:13	  File "<frozen importlib._bootstrap>", line 702, in _load
    18-Mar-2021 01:02:13	  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
    18-Mar-2021 01:02:13	  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
    18-Mar-2021 01:02:13	  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    18-Mar-2021 01:02:13	  File "/home/bamboo/bamboo-agent-home/xml-data/build-dir/CAMKES-CUT202-UNIT/camkes/camkes/templates/__init__.py", line 22, in <module>
    18-Mar-2021 01:02:13	    from . import macros, arch_helpers
    18-Mar-2021 01:02:13	  File "/home/bamboo/bamboo-agent-home/xml-data/build-dir/CAMKES-CUT202-UNIT/camkes/camkes/templates/macros.py", line 18, in <module>
    18-Mar-2021 01:02:13	    from capdl import ASIDPool, CNode, Endpoint, Frame, IODevice, IOPageTable, \
    18-Mar-2021 01:02:13	ModuleNotFoundError: No module named 'capdl'
    18-Mar-2021 01:02:13	
    18-Mar-2021 01:02:13	----------------------------------------------------------------------
    18-Mar-2021 01:02:13	Ran 177 tests in 1.936s
    18-Mar-2021 01:02:13	
    18-Mar-2021 01:02:13	FAILED (SKIP=1, errors=1)
    18-Mar-2021 01:02:13	+ exit 0
    18-Mar-2021 01:02:13	Finished task 'Run unit tests' with result: Success
    18-Mar-2021 01:02:13	Starting task 'Parse results' of type 'com.atlassian.bamboo.plugins.testresultparser:task.testresultparser.junit'
    18-Mar-2021 01:02:13	Parsing test results under /home/bamboo/bamboo-agent-home/xml-data/build-dir/CAMKES-CUT202-UNIT...
    18-Mar-2021 01:02:13	Failing task since 1 failing test cases were found.
    18-Mar-2021 01:02:13	Finished task 'Parse results' with result: Failed
    18-Mar-2021 01:02:13	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    18-Mar-2021 01:02:14	+ chmod -R o+rwx /home/bamboo/bamboo-agent-home/xml-data/build-dir/CAMKES-CUT202-UNIT
    18-Mar-2021 01:02:14	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    18-Mar-2021 01:02:14	Starting task 'Accumulate success marker [UNIT.CAmkES_Unit_Tests.success]' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    18-Mar-2021 01:02:15	+ '[' -f UNIT.success ']'
    18-Mar-2021 01:02:15	+ echo UNIT=FAILURE
    18-Mar-2021 01:02:15	Finished task 'Accumulate success marker [UNIT.CAmkES_Unit_Tests.success]' with result: Success
    18-Mar-2021 01:02:15	Running post build plugin 'Docker Container Cleanup'
    18-Mar-2021 01:02:15	Running post build plugin 'NCover Results Collector'
    18-Mar-2021 01:02:15	Running post build plugin 'Clover Results Collector'
    18-Mar-2021 01:02:15	Running post build plugin 'npm Cache Cleanup'
    18-Mar-2021 01:02:15	Running post build plugin 'Artifact Copier'
    18-Mar-2021 01:02:15	Publishing an artifact: success_CAmkES_Unit_Tests_UNIT
    18-Mar-2021 01:02:15	Finished publishing of artifact Non required shared artifact: [success_CAmkES_Unit_Tests_UNIT], pattern: [*.CAmkES_Unit_Tests.success] anchored at: [.] in 21.12 ms
    18-Mar-2021 01:02:15	Successfully removed working directory at '/home/bamboo/bamboo-agent-home/xml-data/build-dir/CAMKES-CUT202-UNIT'
    18-Mar-2021 01:02:15	Finalising the build...
    18-Mar-2021 01:02:15	Stopping timer.
    18-Mar-2021 01:02:15	Build CAMKES-CUT202-UNIT-1 completed.
    18-Mar-2021 01:02:15	02308b7a-4428-4fec-b1d8-96ef73f82a5f277517598
    18-Mar-2021 12:02:16	Running on server: post build plugin 'NCover Results Collector'
    18-Mar-2021 12:02:16	Running on server: post build plugin 'Build Hanging Detection Configuration'
    18-Mar-2021 12:02:16	Running on server: post build plugin 'Clover Delta Calculator'
    18-Mar-2021 12:02:16	Running on server: post build plugin 'Maven Dependencies Postprocessor'
    18-Mar-2021 12:02:16	All post build plugins have finished
    18-Mar-2021 12:02:16	Generating build results summary...
    18-Mar-2021 12:02:16	Saving build results to disk...
    18-Mar-2021 12:02:16	Store variable context...
    18-Mar-2021 12:02:16	Indexing build results...
    18-Mar-2021 12:02:16	Finished building CAMKES-CUT202-UNIT-1.


This is the most I can report on right now, sorry!

**Comment by lsf37** [comment]
I think this failed before already (and we should fix it). Is it working from a too-old manifest? It seems to not be finding the capDL tools.

**Comment by kent-mcleod** [comment]
A capdl repo should be checked out and placed here according to the test invocation: `PYTHONPATH=../capdl/python-capdl-tool`

**Comment by lsf37** [comment]
> A capdl repo should be checked out and placed here according to the test invocation: `PYTHONPATH=../capdl/python-capdl-tool`

Right, the bamboo config only checks out `camkes-tool` under `camkes`. If it needs both, then it should really be using a manifest, though, otherwise it'll be unclear later which revisions of what belong to which test.

I'll add capDL as a quick fix and open a Jira issue for doing this properly.

**Comment by lsf37** [comment]
> Right, the bamboo config only checks out `camkes-tool` under `camkes`. If it needs both, then it should really be using a manifest, though, otherwise it'll be unclear later which revisions of what belong to which test.
> 
> I'll add capDL as a quick fix and open a Jira issue for doing this properly.

As added benefit, the disappearance of the capDL repo in bamboo was my fault (accidental delete when I added the notification for it). Now working happily again.

**Pull request merged**
