### PR TITLE
seL4HardwareInterrupt: Fix compilation warning

### PR DESCRIPTION
**Pull request by kent-mcleod**
Define a compatible IRQ Ack function to be passed to irq_callback_fn_t
@ssrg-bamboo `test`

### CODE REVIEW

**Comment by axel-h** [comment]
thanks for this fix, my build works again with this one

**Comment by kent-mcleod** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Pull request merged**
