### PR TITLE
libsel4camkes: add include guard

### PR DESCRIPTION
**Pull request by axel-h**

### CODE REVIEW

**Review by kent-mcleod — APPROVED** [review]

**Review by xurtis — APPROVED** [review]

**Comment by axel-h** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Comment by oliver-wm** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Comment by oliver-wm** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by axel-h** [comment]
merged in https://github.com/seL4/camkes-tool/commit/c1f7000c83513d9c4591a4134b646e76d9ac0829

**Pull request closed without merging**
