### PR TITLE
serial: rename Serial.camkes files

### PR DESCRIPTION
**Pull request by chrisguikema**
This fixes an "unknown reference to 'Serial'" issue seen on MacOS.

Issue described [here](https://github.com/seL4/camkes-tool/issues/119)

### CODE REVIEW

**Comment by axel-h** [comment]
I'm not sure I really understand the bug here. But the renaming appears a good idea to have file names that are a bit more unique and thus less likely to cause confusion with `<camkes-tool>/components/arch/<arch>/arch/serial.camkes`

**Review by axel-h — APPROVED** [review]
Given these files were added recently, there is not much history on the name. From my side renaming them ok. Clarifying in detail why the file names are case insensitive on MacOS/Docker could be a follow-up action then.

**Comment by lsf37** [comment]
The name would definitely be case insensitive on Mac, because docker would be using the host file system for this, i.e. this is not inside the container really, but something from inside the container is accessing it. (And standard file system for Mac is case-insensitive).

**Comment by axel-h** [comment]
So, does this mean you are also ok with merging this? It seem on a practical it's better to support case insensitivity also.

**Review by kent-mcleod — APPROVED** [review]

**Review by lsf37 — APPROVED** [review]
Yes, also happy with merging it, should have hit the approve button directly.

**Pull request merged**
